version: '3.8'
services:
  webcontent:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  nginx:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'

