version: '3.8'
services:
  webcontent:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - reactapp:./frontend/build/

  nginx:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - reactapp:/usr/share/nginx/html/frontend

volumes:
  reactapp:
