version: '3.8'
services:
  webimage:
    container_name: 'web-content'
    image: ${WEB_IMAGE}
    ports:
      - '3000:3000'
    volumes:
      - reactapp:/frontend/build/

  nginximage:
    container_name: 'nginx-content'
    image: ${NGINX_IMAGE}
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - reactapp:/usr/share/nginx/html/frontend
      - ./certs:/etc/nginx/tls:ro

volumes:
  reactapp:
