name: Github actions to Deploy React Application

on:
  push:
    branches:
      - main
    paths:
      - 'FrontEnd/**'
      - 'Nginx/**'
jobs:
  ReactAppDeployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Building docker image
        working-directory: ./FrontEnd
        run: |
          docker-compose build --build-arg SLS_URL=${{ secrets.REACT_APP_SERVERLESS_URL }}

      - name: Push images to docker hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker image ls
          docker tag excelcsvtotable-nginx:latest $DOCKER_USER/serverless-nginx:latest
          docker tag excelcsvtotable-webcontent:latest $DOCKER_USER/serverless-reactapp:latest
          docker push $DOCKER_USER/serverless-nginx:latest
          docker push $DOCKER_USER/serverless-reactapp:latest
