name: Github actions to Deploy React Application

on:
  push:
    paths:
      - 'frontEnd/**'
jobs:
  ServerlessAppDeployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Backend
        working-directory: ./FrontEnd
        run: |
          echo "Frontend React App"
          ls
