name: Github actions to Deploy React Application

on:
  push:
    branches:
      - main
    paths:
      - 'FrontEnd/**'
      - 'Nginx/**'
jobs:
  ReactAppDeployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Building docker images
        run: |
          ls
          docker buildx prune -f 
          docker compose -f docker-compose-ci.yml build --build-arg SLS_URL=${{ secrets.REACT_APP_SERVERLESS_URL }}

      - name: Push images to docker hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker image ls
          docker tag excel-csvtotable-nginx:latest $DOCKER_USER/serverless-nginx:latest
          docker tag excel-csvtotable-webcontent:latest $DOCKER_USER/serverless-reactapp:latest
          docker push $DOCKER_USER/serverless-nginx:latest
          docker push $DOCKER_USER/serverless-reactapp:latest

  DeployToEC2Instance:
    runs-on: ubuntu-latest
    needs: ReactAppDeployment
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy docker compose file to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r ./docker-compose-prod.yml ${{secrets.REMOTE_USER}}@${{ secrets.REMOTE_HOST }}

      - name: Login to EC2 and run the docker images
        uses: appleboy/ssh-action@v1.0.3
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          script: |
            pwd
            ls
            sudo WEB_IMAGE=${{ secrets.WEB_IMAGE }} NGINX_IMAGE=${{ secrets.NGINX_IMAGE }} docker compose -f docker-compose-prod.yml up
