name: Github actions to Deploy React Application

on:
  push:
    branches:
      - main
    paths:
      - 'FrontEnd/**'
      - 'Nginx/**'
jobs:
  ReactAppDeployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Building docker images
        run: |
          ls
          docker buildx prune -f 
          docker volume prune -f
          docker-compose -f docker-compose-ci.yml build --build-arg SLS_URL=${{ secrets.REACT_APP_SERVERLESS_URL }} --no-cache

      - name: Push images to docker hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker image ls
          docker tag excel-csvtotable_nginx:latest $DOCKER_USER/serverless-nginx:${{ github.sha }}
          docker tag excel-csvtotable_webcontent:latest $DOCKER_USER/serverless-reactapp:${{ github.sha }}
          docker push $DOCKER_USER/serverless-nginx:${{ github.sha }}
          docker push $DOCKER_USER/serverless-reactapp:${{ github.sha }}

  DeployToEC2Instance:
    runs-on: ubuntu-latest
    needs: ReactAppDeployment
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: create a pem file
        run: |
          cat > reactapp.pem << EOL
          ${{ secrets.SSH_KEY }}
          EOL
          ls -ltr
          chmod 400 reactapp.pem
          ls -ltr
          sudo scp -i reactapp.pem -v -o StrictHostKeyChecking=no docker-compose-prod.yml ubuntu@${{ secrets.HOST_SCP }}:~/.

      - name: Login to EC2 and run the docker images
        uses: appleboy/ssh-action@v1.0.3
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          script: |
            ls
            sudo docker ps -a
            sudo docker image ls
            sudo docker ps -q | xargs sudo docker stop
            sudo docker ps -a -q | xargs sudo docker rm
            sudo docker rmi $(sudo docker images -q)
            sudo docker volume prune -f -a
            sudo docker pull aaketk/serverless-reactapp:${{ github.sha }} 
            sudo docker pull aaketk/serverless-nginx:${{ github.sha }}
            sudo WEB_IMAGE=aaketk/serverless-reactapp:${{ github.sha }} NGINX_IMAGE=aaketk/serverless-nginx:${{ github.sha }} docker-compose -f docker-compose-prod.yml up -d
