name: Github actions to Deploy React Application

on:
  push:
    branches:
      - main
    paths:
      - 'frontEnd/**'
jobs:
  ServerlessAppDeployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: FrontEnd
        run: |
          echo "Frontend React App"
          ls
