name: Github actions to Deploy Serverless Application

on:
  push:
    branches:
      - main
    paths:
      - 'serverlessBackend/**'
jobs:
  ServerlessAppDeployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18

      - name: Install node modules
        working-directory: ./serverlessBackend
        run: npm install

      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: -c "cd ./serverlessBackend && serverless deploy"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
