name: Github actions to Deploy Serverless Application

on:
  push:
    branches:
      - main
    paths:
      - 'serverlessBackend/**'
jobs:
  ServerlessAppDeployment:
    runs-on: ubuntu-latest
    if: github.event_path == 'serverlessBackend'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Backend
        run: |
          echo "Serverless App"
          ls
